# Generated by Django 2.0.8 on 2018-09-26 14:10

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(default='Cake Creativity...', max_length=280)),
                ('image', models.ImageField(blank=True, upload_to=home.models.get_upload_file_name)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
